config:
  application: application_name
  group: "GROUP"
  title: "ProgettiLAB"
  expired_days: 5
  email: 'test@test.com'
  template: 'Template1' #Insert the last name of report's template
  site:
    url: ""
    smtp: ""
    domain_name: ""
  logo1:
    image: "" #Insert image name with extension example: image.png
    link: "" #Insert link example: http://www.google.com
  logo2:
    image: "" #Insert image name with extension example: image.png
    link: "" #Insert link example: http://www.google.com
  logo3:
    image: "" #Insert image name with extension example: image.png
    link: "" #Insert link example: http://www.google.com
  copyright:
    title: ISPRA
    link: http://www.isprambiente.gov.it
  footer:
    links:
      -
        icon: globe
        title: ProgettiLAB
        link: "" #Insert link example: http://www.google.com
radon_types:
  nothing: 0
  concentration: 1
  exposure: 2
report_types:
  single: 0
  multiple: 1
reportpdf:
  passwdforopen: ''
  logo: ""
  society: ""
  title: "ProgettiLAB"
  subtitle: "Gestione progetti e attività di un laboratorio"
  bottom:
    detail:
    design:
    timetable:
    sample:
    analisy:
    multiple:
    destroyer:
    log:
  author: "AUTHOR NAME"
  subject: "SUBJECT "
  keywords: "keywords"
  creator: "CREATOR NAME"
  producer: "PRODUCER NAME"
  footer: false
  qrcode: false
  barcode: false
  notes: false

news:
  title: ''
  link: ''
  source_link: ''

matomo:
  idsite: 1
  link: ""
