config:
  application: progettilab
  group: "ISIN"
  title: "Ispettorato nazionale per la sicurezza nucleare e la radioprotezione"
  expired_days: 5
  email: 'procedimenti.ural@isinucleare.it'
  template: 'Template1' #Insert the last name of report's template
  site:
    url: <%= Rails.application.credentials.mail[:url] %>
    protocol: <%= Rails.application.credentials.mail[:protocol] %>
    smtp: <%= Rails.application.credentials.mail[:smtp] %>
    port: <%= Rails.application.credentials.mail[:port] %>
    domain_name: <%= Rails.application.credentials.mail[:domain_name] %>
  logo1:
    image: "logo_ministero.png"
    link: "http://www.isinucleare.it/"
  logo2:
    image: "logo_isin.jpg"
    link: "http://www.isinucleare.it/"
  logo3:
    image: "foglia.png"
    link: "http://www.isinucleare.it/"
  copyright:
    title: ISIN
    link: "#"
  footer:
    links:
      -
        icon: globe
        title: Gestione Procedimenti attività URAL
        link: "#" #Insert link example: http://www.google.com
radon_types:
  nothing: 0
  concentration: 1
  exposure: 2
report_types:
  single: 0
  multiple: 1
reportpdf:
  passwdforopen: ''
  logo: "logo_stampa_isin.png"
  society: "logo_stampa_isin.png"
  title: "Gestione proc/att"
  subtitle: "Ispettorato nazionale\nper la sicurezza nucleare\ne la radioprotezione"
  bottom:
    detail:
    design:
    timetable:
    sample:
    analisy: "Nome e indirizzo del laboratorio:\r\nISIN - Ispettorato nazionale per la sicurezza nucleare e la radioprotezione\r\nVia Capitan Bavastro, 116 – 00154 Roma"
    multiple:
    destroyer:
    log:
  author: "ISIN"
  subject: "Proc/Att "
  keywords: "proc/att"
  creator: "ISIN"
  producer: "ISIN"
  footer: false
  qrcode: false
  barcode: false
  notes: false

news:
  title: ''
  link: ''
  source_link: ''

matomo:
  idsite: 1
  link: ""
